apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schema-registry
  template:
    metadata:
      labels:
        app: schema-registry
    spec:
      containers:
        - name: schema-registry
          image: apicurio/apicurio-registry-mem:2.4.2.Final
          ports:
            - containerPort: 8080
          env:
            - name: REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: kafka:9092