apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: redpanda
          image: docker.io/redpandadata/redpanda:v23.2.15
          imagePullPolicy: Always
          ports:
            - containerPort: 9092

          command:
            - redpanda
            - start
            - --overprovisioned
            - --smp
            - "1"
            - --memory
            - "512M"
            - --reserve-memory
            - "0M"
            - --node-id
            - "0"
            - --check=false
            - --kafka-addr
            - PLAINTEXT://0.0.0.0:9092
            - --advertise-kafka-addr
            - PLAINTEXT://kafka:9092

          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "300m"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  selector:
    app: kafka
  ports:
    - port: 9092
      targetPort: 9092